apiVersion: v1
kind: Service
metadata:
  name: grafana-svc
  namespace: monitoring-ns-local
spec:
  selector:
    app: grafana-svc
  type: LoadBalancer
  ports:
   -  protocol: TCP
      port: 3000
      targetPort: 3000
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: grafana-cm
data:
  datasources.yaml: |
    apiVersion: 1

    datasources:
      - name: Loki
        type: loki
        access: proxy
        url: http://loki-svc.monitoring-ns-local.svc.cluster.local:3100
        version: 1
        editable: false
        isDefault: true
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: grafana-svc
  namespace: monitoring-ns-local
  labels:
    app: grafana-svc
    group: svc
spec:
  replicas: 1
  selector:
    matchLabels:
      app: grafana-svc
  template:
    metadata:
      labels:
        app: grafana-svc
        type: svc
    spec:
      containers:
        - name: grafana-svc
          image: grafana/grafana:latest
          ports:
            - containerPort: 3000
          env:
          - name: GF_AUTH_ANONYMOUS_ENABLED
            value: 'true'
          - name: GF_AUTH_ANONYMOUS_ORG_ROLE
            value: 'Admin'
          - name: GF_AUTH_DISABLE_LOGIN_FORM
            value: 'true'
          volumeMounts:
            - mountPath: /etc/grafana/provisioning/datasources
              name: datasources
      volumes:
        - name: datasources
          configMap:
            name: grafana-cm
---
apiVersion: v1
kind: Service
metadata:
  name: loki-svc
  namespace: monitoring-ns-local
spec:
  selector:
    app: loki-svc
  type: LoadBalancer
  ports:
   -  protocol: TCP
      port: 3100
      targetPort: 3100
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: loki-svc
  namespace: monitoring-ns-local
  labels:
    app: loki-svc
    group: svc
spec:
  replicas: 1
  selector:
    matchLabels:
      app: loki-svc
  template:
    metadata:
      labels:
        app: loki-svc
        type: svc
    spec:
      containers:
        - name: loki-svc
          image: grafana/loki:latest
          ports:
            - containerPort: 3100
---
# apiVersion: v1
# kind: Service
# metadata:
#   name: prometheus-svc
#   namespace: monitoring-ns-local
# spec:
#   selector:
#     app: prometheus-svc
#   type: LoadBalancer
#   ports:
#    -  protocol: TCP
#       port: 9090
#       targetPort: 9090
# ---
# apiVersion: apps/v1
# kind: Deployment
# metadata:
#   name: prometheus-svc
#   namespace: monitoring-ns-local
#   labels:
#     app: prometheus-svc
#     group: svc
# spec:
#   replicas: 1
#   selector:
#     matchLabels:
#       app: prometheus-svc
#   template:
#     metadata:
#       labels:
#         app: prometheus-svc
#         type: svc
#     spec:
#       containers:
#         - name: prometheus-svc
#           image: prom/prometheus:v2.35.0
#           ports:
#             - containerPort: 9090
