---
apiVersion: v1
kind: ConfigMap
metadata:
  namespace: monitoring-ns-local
  name: promtail
data:
  promtail.yaml: |
    server:
      http_listen_port: 9080
      grpc_listen_port: 0

    positions:
      filename: /tmp/positions.yaml

    clients:
      - url: http://loki-svc.monitoring-ns-local.svc.cluster.local:3100/loki/api/v1/push

    scrape_configs:
      - job_name: varlogs
        static_configs:
          - targets:
              - localhost
            labels:
              job: varlogs
              node_name: "${HOSTNAME}"
              __path__: /var/log/*log
          - targets:
              - localhost
            labels:
              job: varlogs
              node_name: "${HOSTNAME}"
              __path__: /var/log/apt/*log
          - targets:
              - localhost
            labels:
              job: varlogs
              node_name: "${HOSTNAME}"
              __path__: /var/log/unattended-upgrades/*log
        pipeline_stages:
          - drop:
              expression: 'Failed to set up mount unit: Invalid argument$'
          - drop:
              expression: 'message repeated [0-9]+ times: \\[ Failed to set up mount unit: Invalid argument\\]$'
      - job_name: systemd
        journal:
          json: false
          labels:
            job: systemd
            node_name: "${HOSTNAME}"
          path: /var/log/journal
        relabel_configs:
          - source_labels:
              - __journal__systemd_unit
            action: replace
            target_label: unit
        pipeline_stages:
          - drop:
              expression: '^Failed to set up mount unit: Invalid argument$'
      # - job_name: varlogscontainers
      #   static_configs:
      #     - targets:
      #         - localhost
      #       labels:
      #         job: varlogscontainers
      #         node_name: "${HOSTNAME}"
      #         __path__: /var/log/containers/*log
      #   pipeline_stages:
      #     - drop:
      #         expression: 'Failed to set up mount unit: Invalid argument$'
      #     - drop:
      #         expression: 'message repeated [0-9]+ times: \\[ Failed to set up mount unit: Invalid argument\\]$'
      # - job_name: kubernetes-audit
      #   static_configs:
      #     - targets:
      #         - localhost
      #       labels:
      #         job: kubernetes-audit
      #         node_name: "${HOSTNAME}"
      #         __path__: /var/log/containers/*log
      - job_name: kubernetes-pods
        kubernetes_sd_configs:
          - role: pod
        relabel_configs:
          - source_labels: [__meta_kubernetes_pod_annotation_grafana_com_logs_enabled]
            action: keep
            regex: "true"
          - source_labels: [__meta_kubernetes_namespace]
            action: replace
            target_label: namespace
          - source_labels: [__meta_kubernetes_pod_name]
            action: replace
            target_label: pod
          - source_labels: [__meta_kubernetes_container_name]
            action: replace
            target_label: container
          - source_labels: [__meta_kubernetes_pod_node_name]
            action: replace
            target_label: node
        # Example for file-based logs (adjust paths accordingly)
        pipeline_stages:
          - docker: {}
---
apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: promtail
  namespace: monitoring-ns-local
spec:
  updateStrategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 0
      maxUnavailable: 1
  selector:
    matchLabels:
      app: promtail
  template:
    metadata:
      labels:
        app: promtail
    spec:
      serviceAccountName: promtail
      securityContext:
        runAsNonRoot: false
      containers:
        - name: promtail
          image: grafana/promtail:latest
          args:
            - -config.file=/promtail/config/promtail.yaml
            # - -config.expand-env=true
          env:
            - name: HOSTNAME
              valueFrom:
                fieldRef:
                  fieldPath: spec.nodeName
          securityContext:
            runAsUser: 0
          volumeMounts:
            - mountPath: /promtail/config
              name: config
              readOnly: true
            - mountPath: /promtail/run
              name: run
            - mountPath: /var/log
              mountPropagation: HostToContainer
              name: varlogs
              readOnly: true
            - mountPath: /var/lib/docker/containers
              mountPropagation: HostToContainer
              name: varlibcontainers
              readOnly: true
      # tolerations:
      #   - effect: NoSchedule
      #     operator: Exists
      volumes:
        - name: config
          configMap:
            name: promtail
        # - name: tls
        #   secret:
        #     secretName: promtail-tls
        - name: run
          hostPath:
            path: /run/promtail
        #     type: "DirectoryOrCreate"
        - name: varlogs
          hostPath:
            path: /var/log
            type: ""
        - name: varlibcontainers
          hostPath:
            path: /var/lib/docker/containers
            type: ""
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: promtail
subjects:
  - kind: ServiceAccount
    name: promtail
    namespace: monitoring-ns-local
roleRef:
  kind: ClusterRole
  name: promtail
  apiGroup: rbac.authorization.k8s.io
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: promtail
rules:
  - apiGroups: [""] # "" indicates the core API group
    resources:
      - namespaces
      - pods
    verbs:
      - get
      - watch
      - list
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: promtail
  namespace: monitoring-ns-local
