// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.30.0
// 	protoc        v3.21.12
// source: pkg/category/pb/category.proto

package pb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// FindOne
type FindOneCategoryData struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id   int64  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Name string `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
}

func (x *FindOneCategoryData) Reset() {
	*x = FindOneCategoryData{}
	if protoimpl.UnsafeEnabled {
		mi := &file_pkg_category_pb_category_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *FindOneCategoryData) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FindOneCategoryData) ProtoMessage() {}

func (x *FindOneCategoryData) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_category_pb_category_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FindOneCategoryData.ProtoReflect.Descriptor instead.
func (*FindOneCategoryData) Descriptor() ([]byte, []int) {
	return file_pkg_category_pb_category_proto_rawDescGZIP(), []int{0}
}

func (x *FindOneCategoryData) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *FindOneCategoryData) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

type FindOneCategoryRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id int64 `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
}

func (x *FindOneCategoryRequest) Reset() {
	*x = FindOneCategoryRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_pkg_category_pb_category_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *FindOneCategoryRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FindOneCategoryRequest) ProtoMessage() {}

func (x *FindOneCategoryRequest) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_category_pb_category_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FindOneCategoryRequest.ProtoReflect.Descriptor instead.
func (*FindOneCategoryRequest) Descriptor() ([]byte, []int) {
	return file_pkg_category_pb_category_proto_rawDescGZIP(), []int{1}
}

func (x *FindOneCategoryRequest) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

type FindOneCategoryResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Status int64                `protobuf:"varint,1,opt,name=status,proto3" json:"status,omitempty"`
	Error  string               `protobuf:"bytes,2,opt,name=error,proto3" json:"error,omitempty"`
	Data   *FindOneCategoryData `protobuf:"bytes,3,opt,name=data,proto3" json:"data,omitempty"`
}

func (x *FindOneCategoryResponse) Reset() {
	*x = FindOneCategoryResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_pkg_category_pb_category_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *FindOneCategoryResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FindOneCategoryResponse) ProtoMessage() {}

func (x *FindOneCategoryResponse) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_category_pb_category_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FindOneCategoryResponse.ProtoReflect.Descriptor instead.
func (*FindOneCategoryResponse) Descriptor() ([]byte, []int) {
	return file_pkg_category_pb_category_proto_rawDescGZIP(), []int{2}
}

func (x *FindOneCategoryResponse) GetStatus() int64 {
	if x != nil {
		return x.Status
	}
	return 0
}

func (x *FindOneCategoryResponse) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

func (x *FindOneCategoryResponse) GetData() *FindOneCategoryData {
	if x != nil {
		return x.Data
	}
	return nil
}

// FindAll
type FindCategoryData struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id   int64  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Name string `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
}

func (x *FindCategoryData) Reset() {
	*x = FindCategoryData{}
	if protoimpl.UnsafeEnabled {
		mi := &file_pkg_category_pb_category_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *FindCategoryData) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FindCategoryData) ProtoMessage() {}

func (x *FindCategoryData) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_category_pb_category_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FindCategoryData.ProtoReflect.Descriptor instead.
func (*FindCategoryData) Descriptor() ([]byte, []int) {
	return file_pkg_category_pb_category_proto_rawDescGZIP(), []int{3}
}

func (x *FindCategoryData) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *FindCategoryData) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

type FindAllCategoriesRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id int64 `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
}

func (x *FindAllCategoriesRequest) Reset() {
	*x = FindAllCategoriesRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_pkg_category_pb_category_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *FindAllCategoriesRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FindAllCategoriesRequest) ProtoMessage() {}

func (x *FindAllCategoriesRequest) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_category_pb_category_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FindAllCategoriesRequest.ProtoReflect.Descriptor instead.
func (*FindAllCategoriesRequest) Descriptor() ([]byte, []int) {
	return file_pkg_category_pb_category_proto_rawDescGZIP(), []int{4}
}

func (x *FindAllCategoriesRequest) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

type FindAllCategoriesResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Status int64               `protobuf:"varint,1,opt,name=status,proto3" json:"status,omitempty"`
	Error  string              `protobuf:"bytes,2,opt,name=error,proto3" json:"error,omitempty"`
	Data   []*FindCategoryData `protobuf:"bytes,3,rep,name=data,proto3" json:"data,omitempty"`
}

func (x *FindAllCategoriesResponse) Reset() {
	*x = FindAllCategoriesResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_pkg_category_pb_category_proto_msgTypes[5]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *FindAllCategoriesResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FindAllCategoriesResponse) ProtoMessage() {}

func (x *FindAllCategoriesResponse) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_category_pb_category_proto_msgTypes[5]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FindAllCategoriesResponse.ProtoReflect.Descriptor instead.
func (*FindAllCategoriesResponse) Descriptor() ([]byte, []int) {
	return file_pkg_category_pb_category_proto_rawDescGZIP(), []int{5}
}

func (x *FindAllCategoriesResponse) GetStatus() int64 {
	if x != nil {
		return x.Status
	}
	return 0
}

func (x *FindAllCategoriesResponse) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

func (x *FindAllCategoriesResponse) GetData() []*FindCategoryData {
	if x != nil {
		return x.Data
	}
	return nil
}

// FindPagged
type FindPaggedCategoriesData struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id           int64  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Name         string `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	DepartmentId int64  `protobuf:"varint,3,opt,name=department_id,json=departmentId,proto3" json:"department_id,omitempty"`
	Code         string `protobuf:"bytes,4,opt,name=code,proto3" json:"code,omitempty"`
}

func (x *FindPaggedCategoriesData) Reset() {
	*x = FindPaggedCategoriesData{}
	if protoimpl.UnsafeEnabled {
		mi := &file_pkg_category_pb_category_proto_msgTypes[6]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *FindPaggedCategoriesData) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FindPaggedCategoriesData) ProtoMessage() {}

func (x *FindPaggedCategoriesData) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_category_pb_category_proto_msgTypes[6]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FindPaggedCategoriesData.ProtoReflect.Descriptor instead.
func (*FindPaggedCategoriesData) Descriptor() ([]byte, []int) {
	return file_pkg_category_pb_category_proto_rawDescGZIP(), []int{6}
}

func (x *FindPaggedCategoriesData) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *FindPaggedCategoriesData) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *FindPaggedCategoriesData) GetDepartmentId() int64 {
	if x != nil {
		return x.DepartmentId
	}
	return 0
}

func (x *FindPaggedCategoriesData) GetCode() string {
	if x != nil {
		return x.Code
	}
	return ""
}

type FindPaggedCategoriesRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	DepartmentId int64 `protobuf:"varint,1,opt,name=departmentId,proto3" json:"departmentId,omitempty"`
	CurrentPage  int64 `protobuf:"varint,2,opt,name=currentPage,proto3" json:"currentPage,omitempty"`
	PageSize     int64 `protobuf:"varint,3,opt,name=pageSize,proto3" json:"pageSize,omitempty"`
}

func (x *FindPaggedCategoriesRequest) Reset() {
	*x = FindPaggedCategoriesRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_pkg_category_pb_category_proto_msgTypes[7]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *FindPaggedCategoriesRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FindPaggedCategoriesRequest) ProtoMessage() {}

func (x *FindPaggedCategoriesRequest) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_category_pb_category_proto_msgTypes[7]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FindPaggedCategoriesRequest.ProtoReflect.Descriptor instead.
func (*FindPaggedCategoriesRequest) Descriptor() ([]byte, []int) {
	return file_pkg_category_pb_category_proto_rawDescGZIP(), []int{7}
}

func (x *FindPaggedCategoriesRequest) GetDepartmentId() int64 {
	if x != nil {
		return x.DepartmentId
	}
	return 0
}

func (x *FindPaggedCategoriesRequest) GetCurrentPage() int64 {
	if x != nil {
		return x.CurrentPage
	}
	return 0
}

func (x *FindPaggedCategoriesRequest) GetPageSize() int64 {
	if x != nil {
		return x.PageSize
	}
	return 0
}

type FindPaggedCategoriesResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Status    int64                       `protobuf:"varint,1,opt,name=status,proto3" json:"status,omitempty"`
	Error     string                      `protobuf:"bytes,2,opt,name=error,proto3" json:"error,omitempty"`
	TotalPage int64                       `protobuf:"varint,3,opt,name=totalPage,proto3" json:"totalPage,omitempty"`
	Data      []*FindPaggedCategoriesData `protobuf:"bytes,4,rep,name=data,proto3" json:"data,omitempty"`
}

func (x *FindPaggedCategoriesResponse) Reset() {
	*x = FindPaggedCategoriesResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_pkg_category_pb_category_proto_msgTypes[8]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *FindPaggedCategoriesResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FindPaggedCategoriesResponse) ProtoMessage() {}

func (x *FindPaggedCategoriesResponse) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_category_pb_category_proto_msgTypes[8]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FindPaggedCategoriesResponse.ProtoReflect.Descriptor instead.
func (*FindPaggedCategoriesResponse) Descriptor() ([]byte, []int) {
	return file_pkg_category_pb_category_proto_rawDescGZIP(), []int{8}
}

func (x *FindPaggedCategoriesResponse) GetStatus() int64 {
	if x != nil {
		return x.Status
	}
	return 0
}

func (x *FindPaggedCategoriesResponse) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

func (x *FindPaggedCategoriesResponse) GetTotalPage() int64 {
	if x != nil {
		return x.TotalPage
	}
	return 0
}

func (x *FindPaggedCategoriesResponse) GetData() []*FindPaggedCategoriesData {
	if x != nil {
		return x.Data
	}
	return nil
}

var File_pkg_category_pb_category_proto protoreflect.FileDescriptor

var file_pkg_category_pb_category_proto_rawDesc = []byte{
	0x0a, 0x1e, 0x70, 0x6b, 0x67, 0x2f, 0x63, 0x61, 0x74, 0x65, 0x67, 0x6f, 0x72, 0x79, 0x2f, 0x70,
	0x62, 0x2f, 0x63, 0x61, 0x74, 0x65, 0x67, 0x6f, 0x72, 0x79, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f,
	0x12, 0x08, 0x63, 0x61, 0x74, 0x65, 0x67, 0x6f, 0x72, 0x79, 0x22, 0x39, 0x0a, 0x13, 0x46, 0x69,
	0x6e, 0x64, 0x4f, 0x6e, 0x65, 0x43, 0x61, 0x74, 0x65, 0x67, 0x6f, 0x72, 0x79, 0x44, 0x61, 0x74,
	0x61, 0x12, 0x0e, 0x0a, 0x02, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x03, 0x52, 0x02, 0x69,
	0x64, 0x12, 0x12, 0x0a, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52,
	0x04, 0x6e, 0x61, 0x6d, 0x65, 0x22, 0x28, 0x0a, 0x16, 0x46, 0x69, 0x6e, 0x64, 0x4f, 0x6e, 0x65,
	0x43, 0x61, 0x74, 0x65, 0x67, 0x6f, 0x72, 0x79, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12,
	0x0e, 0x0a, 0x02, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x03, 0x52, 0x02, 0x69, 0x64, 0x22,
	0x7a, 0x0a, 0x17, 0x46, 0x69, 0x6e, 0x64, 0x4f, 0x6e, 0x65, 0x43, 0x61, 0x74, 0x65, 0x67, 0x6f,
	0x72, 0x79, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x16, 0x0a, 0x06, 0x73, 0x74,
	0x61, 0x74, 0x75, 0x73, 0x18, 0x01, 0x20, 0x01, 0x28, 0x03, 0x52, 0x06, 0x73, 0x74, 0x61, 0x74,
	0x75, 0x73, 0x12, 0x14, 0x0a, 0x05, 0x65, 0x72, 0x72, 0x6f, 0x72, 0x18, 0x02, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x05, 0x65, 0x72, 0x72, 0x6f, 0x72, 0x12, 0x31, 0x0a, 0x04, 0x64, 0x61, 0x74, 0x61,
	0x18, 0x03, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x1d, 0x2e, 0x63, 0x61, 0x74, 0x65, 0x67, 0x6f, 0x72,
	0x79, 0x2e, 0x46, 0x69, 0x6e, 0x64, 0x4f, 0x6e, 0x65, 0x43, 0x61, 0x74, 0x65, 0x67, 0x6f, 0x72,
	0x79, 0x44, 0x61, 0x74, 0x61, 0x52, 0x04, 0x64, 0x61, 0x74, 0x61, 0x22, 0x36, 0x0a, 0x10, 0x46,
	0x69, 0x6e, 0x64, 0x43, 0x61, 0x74, 0x65, 0x67, 0x6f, 0x72, 0x79, 0x44, 0x61, 0x74, 0x61, 0x12,
	0x0e, 0x0a, 0x02, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x03, 0x52, 0x02, 0x69, 0x64, 0x12,
	0x12, 0x0a, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x6e,
	0x61, 0x6d, 0x65, 0x22, 0x2a, 0x0a, 0x18, 0x46, 0x69, 0x6e, 0x64, 0x41, 0x6c, 0x6c, 0x43, 0x61,
	0x74, 0x65, 0x67, 0x6f, 0x72, 0x69, 0x65, 0x73, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12,
	0x0e, 0x0a, 0x02, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x03, 0x52, 0x02, 0x69, 0x64, 0x22,
	0x79, 0x0a, 0x19, 0x46, 0x69, 0x6e, 0x64, 0x41, 0x6c, 0x6c, 0x43, 0x61, 0x74, 0x65, 0x67, 0x6f,
	0x72, 0x69, 0x65, 0x73, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x16, 0x0a, 0x06,
	0x73, 0x74, 0x61, 0x74, 0x75, 0x73, 0x18, 0x01, 0x20, 0x01, 0x28, 0x03, 0x52, 0x06, 0x73, 0x74,
	0x61, 0x74, 0x75, 0x73, 0x12, 0x14, 0x0a, 0x05, 0x65, 0x72, 0x72, 0x6f, 0x72, 0x18, 0x02, 0x20,
	0x01, 0x28, 0x09, 0x52, 0x05, 0x65, 0x72, 0x72, 0x6f, 0x72, 0x12, 0x2e, 0x0a, 0x04, 0x64, 0x61,
	0x74, 0x61, 0x18, 0x03, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x1a, 0x2e, 0x63, 0x61, 0x74, 0x65, 0x67,
	0x6f, 0x72, 0x79, 0x2e, 0x46, 0x69, 0x6e, 0x64, 0x43, 0x61, 0x74, 0x65, 0x67, 0x6f, 0x72, 0x79,
	0x44, 0x61, 0x74, 0x61, 0x52, 0x04, 0x64, 0x61, 0x74, 0x61, 0x22, 0x77, 0x0a, 0x18, 0x46, 0x69,
	0x6e, 0x64, 0x50, 0x61, 0x67, 0x67, 0x65, 0x64, 0x43, 0x61, 0x74, 0x65, 0x67, 0x6f, 0x72, 0x69,
	0x65, 0x73, 0x44, 0x61, 0x74, 0x61, 0x12, 0x0e, 0x0a, 0x02, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01,
	0x28, 0x03, 0x52, 0x02, 0x69, 0x64, 0x12, 0x12, 0x0a, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x02,
	0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x12, 0x23, 0x0a, 0x0d, 0x64, 0x65,
	0x70, 0x61, 0x72, 0x74, 0x6d, 0x65, 0x6e, 0x74, 0x5f, 0x69, 0x64, 0x18, 0x03, 0x20, 0x01, 0x28,
	0x03, 0x52, 0x0c, 0x64, 0x65, 0x70, 0x61, 0x72, 0x74, 0x6d, 0x65, 0x6e, 0x74, 0x49, 0x64, 0x12,
	0x12, 0x0a, 0x04, 0x63, 0x6f, 0x64, 0x65, 0x18, 0x04, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x63,
	0x6f, 0x64, 0x65, 0x22, 0x7f, 0x0a, 0x1b, 0x46, 0x69, 0x6e, 0x64, 0x50, 0x61, 0x67, 0x67, 0x65,
	0x64, 0x43, 0x61, 0x74, 0x65, 0x67, 0x6f, 0x72, 0x69, 0x65, 0x73, 0x52, 0x65, 0x71, 0x75, 0x65,
	0x73, 0x74, 0x12, 0x22, 0x0a, 0x0c, 0x64, 0x65, 0x70, 0x61, 0x72, 0x74, 0x6d, 0x65, 0x6e, 0x74,
	0x49, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x03, 0x52, 0x0c, 0x64, 0x65, 0x70, 0x61, 0x72, 0x74,
	0x6d, 0x65, 0x6e, 0x74, 0x49, 0x64, 0x12, 0x20, 0x0a, 0x0b, 0x63, 0x75, 0x72, 0x72, 0x65, 0x6e,
	0x74, 0x50, 0x61, 0x67, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x03, 0x52, 0x0b, 0x63, 0x75, 0x72,
	0x72, 0x65, 0x6e, 0x74, 0x50, 0x61, 0x67, 0x65, 0x12, 0x1a, 0x0a, 0x08, 0x70, 0x61, 0x67, 0x65,
	0x53, 0x69, 0x7a, 0x65, 0x18, 0x03, 0x20, 0x01, 0x28, 0x03, 0x52, 0x08, 0x70, 0x61, 0x67, 0x65,
	0x53, 0x69, 0x7a, 0x65, 0x22, 0xa2, 0x01, 0x0a, 0x1c, 0x46, 0x69, 0x6e, 0x64, 0x50, 0x61, 0x67,
	0x67, 0x65, 0x64, 0x43, 0x61, 0x74, 0x65, 0x67, 0x6f, 0x72, 0x69, 0x65, 0x73, 0x52, 0x65, 0x73,
	0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x16, 0x0a, 0x06, 0x73, 0x74, 0x61, 0x74, 0x75, 0x73, 0x18,
	0x01, 0x20, 0x01, 0x28, 0x03, 0x52, 0x06, 0x73, 0x74, 0x61, 0x74, 0x75, 0x73, 0x12, 0x14, 0x0a,
	0x05, 0x65, 0x72, 0x72, 0x6f, 0x72, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x65, 0x72,
	0x72, 0x6f, 0x72, 0x12, 0x1c, 0x0a, 0x09, 0x74, 0x6f, 0x74, 0x61, 0x6c, 0x50, 0x61, 0x67, 0x65,
	0x18, 0x03, 0x20, 0x01, 0x28, 0x03, 0x52, 0x09, 0x74, 0x6f, 0x74, 0x61, 0x6c, 0x50, 0x61, 0x67,
	0x65, 0x12, 0x36, 0x0a, 0x04, 0x64, 0x61, 0x74, 0x61, 0x18, 0x04, 0x20, 0x03, 0x28, 0x0b, 0x32,
	0x22, 0x2e, 0x63, 0x61, 0x74, 0x65, 0x67, 0x6f, 0x72, 0x79, 0x2e, 0x46, 0x69, 0x6e, 0x64, 0x50,
	0x61, 0x67, 0x67, 0x65, 0x64, 0x43, 0x61, 0x74, 0x65, 0x67, 0x6f, 0x72, 0x69, 0x65, 0x73, 0x44,
	0x61, 0x74, 0x61, 0x52, 0x04, 0x64, 0x61, 0x74, 0x61, 0x32, 0xb4, 0x02, 0x0a, 0x0f, 0x43, 0x61,
	0x74, 0x65, 0x67, 0x6f, 0x72, 0x79, 0x53, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x12, 0x58, 0x0a,
	0x0f, 0x46, 0x69, 0x6e, 0x64, 0x4f, 0x6e, 0x65, 0x43, 0x61, 0x74, 0x65, 0x67, 0x6f, 0x72, 0x79,
	0x12, 0x20, 0x2e, 0x63, 0x61, 0x74, 0x65, 0x67, 0x6f, 0x72, 0x79, 0x2e, 0x46, 0x69, 0x6e, 0x64,
	0x4f, 0x6e, 0x65, 0x43, 0x61, 0x74, 0x65, 0x67, 0x6f, 0x72, 0x79, 0x52, 0x65, 0x71, 0x75, 0x65,
	0x73, 0x74, 0x1a, 0x21, 0x2e, 0x63, 0x61, 0x74, 0x65, 0x67, 0x6f, 0x72, 0x79, 0x2e, 0x46, 0x69,
	0x6e, 0x64, 0x4f, 0x6e, 0x65, 0x43, 0x61, 0x74, 0x65, 0x67, 0x6f, 0x72, 0x79, 0x52, 0x65, 0x73,
	0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22, 0x00, 0x12, 0x5e, 0x0a, 0x11, 0x46, 0x69, 0x6e, 0x64, 0x41,
	0x6c, 0x6c, 0x43, 0x61, 0x74, 0x65, 0x67, 0x6f, 0x72, 0x69, 0x65, 0x73, 0x12, 0x22, 0x2e, 0x63,
	0x61, 0x74, 0x65, 0x67, 0x6f, 0x72, 0x79, 0x2e, 0x46, 0x69, 0x6e, 0x64, 0x41, 0x6c, 0x6c, 0x43,
	0x61, 0x74, 0x65, 0x67, 0x6f, 0x72, 0x69, 0x65, 0x73, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74,
	0x1a, 0x23, 0x2e, 0x63, 0x61, 0x74, 0x65, 0x67, 0x6f, 0x72, 0x79, 0x2e, 0x46, 0x69, 0x6e, 0x64,
	0x41, 0x6c, 0x6c, 0x43, 0x61, 0x74, 0x65, 0x67, 0x6f, 0x72, 0x69, 0x65, 0x73, 0x52, 0x65, 0x73,
	0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22, 0x00, 0x12, 0x67, 0x0a, 0x14, 0x46, 0x69, 0x6e, 0x64, 0x50,
	0x61, 0x67, 0x67, 0x65, 0x64, 0x43, 0x61, 0x74, 0x65, 0x67, 0x6f, 0x72, 0x69, 0x65, 0x73, 0x12,
	0x25, 0x2e, 0x63, 0x61, 0x74, 0x65, 0x67, 0x6f, 0x72, 0x79, 0x2e, 0x46, 0x69, 0x6e, 0x64, 0x50,
	0x61, 0x67, 0x67, 0x65, 0x64, 0x43, 0x61, 0x74, 0x65, 0x67, 0x6f, 0x72, 0x69, 0x65, 0x73, 0x52,
	0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x26, 0x2e, 0x63, 0x61, 0x74, 0x65, 0x67, 0x6f, 0x72,
	0x79, 0x2e, 0x46, 0x69, 0x6e, 0x64, 0x50, 0x61, 0x67, 0x67, 0x65, 0x64, 0x43, 0x61, 0x74, 0x65,
	0x67, 0x6f, 0x72, 0x69, 0x65, 0x73, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22, 0x00,
	0x42, 0x13, 0x5a, 0x11, 0x2e, 0x2f, 0x70, 0x6b, 0x67, 0x2f, 0x63, 0x61, 0x74, 0x65, 0x67, 0x6f,
	0x72, 0x79, 0x2f, 0x70, 0x62, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_pkg_category_pb_category_proto_rawDescOnce sync.Once
	file_pkg_category_pb_category_proto_rawDescData = file_pkg_category_pb_category_proto_rawDesc
)

func file_pkg_category_pb_category_proto_rawDescGZIP() []byte {
	file_pkg_category_pb_category_proto_rawDescOnce.Do(func() {
		file_pkg_category_pb_category_proto_rawDescData = protoimpl.X.CompressGZIP(file_pkg_category_pb_category_proto_rawDescData)
	})
	return file_pkg_category_pb_category_proto_rawDescData
}

var file_pkg_category_pb_category_proto_msgTypes = make([]protoimpl.MessageInfo, 9)
var file_pkg_category_pb_category_proto_goTypes = []interface{}{
	(*FindOneCategoryData)(nil),          // 0: category.FindOneCategoryData
	(*FindOneCategoryRequest)(nil),       // 1: category.FindOneCategoryRequest
	(*FindOneCategoryResponse)(nil),      // 2: category.FindOneCategoryResponse
	(*FindCategoryData)(nil),             // 3: category.FindCategoryData
	(*FindAllCategoriesRequest)(nil),     // 4: category.FindAllCategoriesRequest
	(*FindAllCategoriesResponse)(nil),    // 5: category.FindAllCategoriesResponse
	(*FindPaggedCategoriesData)(nil),     // 6: category.FindPaggedCategoriesData
	(*FindPaggedCategoriesRequest)(nil),  // 7: category.FindPaggedCategoriesRequest
	(*FindPaggedCategoriesResponse)(nil), // 8: category.FindPaggedCategoriesResponse
}
var file_pkg_category_pb_category_proto_depIdxs = []int32{
	0, // 0: category.FindOneCategoryResponse.data:type_name -> category.FindOneCategoryData
	3, // 1: category.FindAllCategoriesResponse.data:type_name -> category.FindCategoryData
	6, // 2: category.FindPaggedCategoriesResponse.data:type_name -> category.FindPaggedCategoriesData
	1, // 3: category.CategoryService.FindOneCategory:input_type -> category.FindOneCategoryRequest
	4, // 4: category.CategoryService.FindAllCategories:input_type -> category.FindAllCategoriesRequest
	7, // 5: category.CategoryService.FindPaggedCategories:input_type -> category.FindPaggedCategoriesRequest
	2, // 6: category.CategoryService.FindOneCategory:output_type -> category.FindOneCategoryResponse
	5, // 7: category.CategoryService.FindAllCategories:output_type -> category.FindAllCategoriesResponse
	8, // 8: category.CategoryService.FindPaggedCategories:output_type -> category.FindPaggedCategoriesResponse
	6, // [6:9] is the sub-list for method output_type
	3, // [3:6] is the sub-list for method input_type
	3, // [3:3] is the sub-list for extension type_name
	3, // [3:3] is the sub-list for extension extendee
	0, // [0:3] is the sub-list for field type_name
}

func init() { file_pkg_category_pb_category_proto_init() }
func file_pkg_category_pb_category_proto_init() {
	if File_pkg_category_pb_category_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_pkg_category_pb_category_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*FindOneCategoryData); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_pkg_category_pb_category_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*FindOneCategoryRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_pkg_category_pb_category_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*FindOneCategoryResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_pkg_category_pb_category_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*FindCategoryData); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_pkg_category_pb_category_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*FindAllCategoriesRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_pkg_category_pb_category_proto_msgTypes[5].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*FindAllCategoriesResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_pkg_category_pb_category_proto_msgTypes[6].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*FindPaggedCategoriesData); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_pkg_category_pb_category_proto_msgTypes[7].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*FindPaggedCategoriesRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_pkg_category_pb_category_proto_msgTypes[8].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*FindPaggedCategoriesResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_pkg_category_pb_category_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   9,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_pkg_category_pb_category_proto_goTypes,
		DependencyIndexes: file_pkg_category_pb_category_proto_depIdxs,
		MessageInfos:      file_pkg_category_pb_category_proto_msgTypes,
	}.Build()
	File_pkg_category_pb_category_proto = out.File
	file_pkg_category_pb_category_proto_rawDesc = nil
	file_pkg_category_pb_category_proto_goTypes = nil
	file_pkg_category_pb_category_proto_depIdxs = nil
}
