apiVersion: v1
kind: Service
metadata:
  name: grafana-svc
  namespace: kamilmucik-lkequiz-maestro
spec:
  selector:
    app: grafana-svc
  type: LoadBalancer
  ports:
   -  protocol: TCP
      port: 3000
      targetPort: 3000
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: grafana-svc
  namespace: kamilmucik-lkequiz-maestro
  labels:
    app: grafana-svc
    group: svc
spec:
  replicas: 1
  selector:
    matchLabels:
      app: grafana-svc
  template:
    metadata:
      labels:
        app: grafana-svc
        type: svc
    spec:
      containers:
        - name: grafana-svc
          image: grafana/grafana:8.2.6
          ports:
            - containerPort: 3000

# http://elasticsearch.kamilmucik-lkequiz-maestro.svc.cluster.local:9200