apiVersion: v1
kind: Service
metadata:
  name: auth-svc
  namespace: lkequiz-local
spec:
  selector:
    app: auth-svc
  # type: LoadBalancer
  ports:
   -  protocol: TCP
      port: 50051
      targetPort: 50051