apiVersion: v1
kind: ConfigMap
metadata:
  name: auth-svc-config
data:
  dev.env: |
    PORT=:50051
    DB_URL=postgresql://user_db:postgres@auth-postgres.lkequiz-local.svc.cluster.local:5433/postgres
    JWT_SECRET_KEY=r43t18sc