apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: auth-postgres-data-pvc
  namespace: lkequiz-local
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: local-path
  resources:
    requests:
      storage: 2Gi