apiVersion: v1
kind: Secret
metadata:
  name: auth-postgres-secret
  labels:
    group: db
type: Opaque
data:
  POSTGRES_DB: cG9zdGdyZXM=
  POSTGRES_USER: dXNlcl9kYg==
  POSTGRES_PASSWORD: cG9zdGdyZXM=