apiVersion: v1
kind: Secret
metadata:
  name: question-postgres-secret
  labels:
    group: db
type: Opaque
data:
  POSTGRES_DB: cG9zdGdyZXM=
  POSTGRES_USER: cXVlc3Rpb25fZGI=
  POSTGRES_PASSWORD: cG9zdGdyZXM=