apiVersion: v1
kind: Service
metadata:
  name: question-postgres
  namespace: lkequiz-local
spec:
  selector:
    app: question-postgres
  # type: LoadBalancer
  ports:
   -  protocol: TCP
      port: 5432
      targetPort: 5432