flyway.url=jdbc:postgresql://db.questions.lkequiz.e-strix.pl:5432/questions

flyway.driver=org.postgresql.Driver

flyway.user=question_user
flyway.password=postgres

flyway.locations=filesystem:/tmp/questions/sql/

flyway.cleanDisabled=false