version: "3"
services:
  api-gateway:
    container_name: gateway
    image: api-gateway:0.0.1
    restart: always
    volumes:
      - ./config/api-gateway/dev.env:/pkg/config/envs/dev.env
    ports:
      - '3001:3000'
  svc-auth:
    container_name: auth
    image: auth-svc:0.0.2
    restart: always
    volumes:
      - ./config/svc-auth/dev.env:/pkg/config/envs/dev.env
    expose:
      - 50051
    ports:
      - '50051:50051'
  svc-question:
    container_name: question
    image: question-svc:0.0.2
    restart: always
    volumes:
      - ./config/svc-question/dev.env:/pkg/config/envs/dev.env
    expose:
      - 50055
    ports:
      - '50055:50055'
  question_db:
    container_name: question_db
    image: postgres:15-alpine
    restart: always
    environment:
      - POSTGRES_USER=question_user
      - POSTGRES_PASSWORD=postgres
      - DATABASE_HOST=127.0.0.1
    ports:
      - '5432:5432'
  user_db:
    container_name: user_db
    image: postgres:14.3-alpine
    restart: always
    environment:
      - POSTGRES_USER=user_db
      - POSTGRES_PASSWORD=postgres
      - DATABASE_HOST=127.0.0.1
    ports:
      - '5433:5432'