---
- name: Deploy service package
  hosts: webserver
  become_user: root
  tasks:
    - name: Delete content & directory
      ansible.builtin.file:
        state: absent
        path: /home/ubuntu/databases/lkequiz/
    - name: Creates directory
      file:
        path: /home/ubuntu/databases/lkequiz/
        state: directory
        # owner: www-data
        # group: www-data
        mode: 0775
    - name: Copy SQL directory
      copy: src=/Users/kamilmuc/ws/lkequiz/database/flyway/ dest=/home/ubuntu/databases/lkequiz/ mode=0777
      tags: lsout
      register: myshell_output
    - name: Execute the script
      command: timeout 60 sh /home/ubuntu/databases/lkequiz/run.sh
      become: yes
      become_method: sudo
      become_user: root
      tags: lsout
      register: myshell_output
    - name: copy the output to a local file
      copy:
        content: "{{ myshell_output.stdout }}"
        dest: "/Users/kamilmuc/ws/lkequiz/ansible/reports/env_{{ ansible_host }}_{{ inventory_hostname }}.txt"
      delegate_to: localhost

