---
- name: Deploy service package
  hosts: webserver
  become_user: root
  tasks:
    - name: Delete content & directory
      ansible.builtin.file:
        state: absent
        path: /home/ubuntu/docker/run/nginx/src/app/app_e_strix_pl
    - name: Creates directory
      file:
        path: /home/ubuntu/docker/run/nginx/src/app/app_e_strix_pl
        state: directory
        # owner: www-data
        # group: www-data
        mode: 0775
    - name: Transfer the Dockerfile
      copy: src=/Users/kamilmuc/ws/lkequiz/webapp/target/lkequiz-web-0.0.1-SNAPSHOT.zip dest=/home/ubuntu/docker/run/nginx/src/app/ mode=0777
      tags: lsout
      register: myshell_output
    - unarchive:
        src: /home/ubuntu/docker/run/nginx/src/app/lkequiz-web-0.0.1-SNAPSHOT.zip
        dest: /home/ubuntu/docker/run/nginx/src/app/app_e_strix_pl/
        remote_src: True
    - name: copy the output to a local file
      copy:
        content: "{{ myshell_output.stdout }}"
        dest: "/Users/kamilmuc/ws/lkequiz/ansible/reports/env_fr_{{ ansible_host }}_{{ inventory_hostname }}.txt"
      delegate_to: localhost