version: "3"
services:
  sonarqube:
    image: sonarqube:9.9.2-community
    # volumes:
    #   - sonarqube_data:/opt/sonarqube/data
    #   - sonarqube_extensions:/opt/sonarqube/extensions
    #   - sonarqube_logs:/opt/sonarqube/logs
    ports:
      - "9001:9000"
    restart: always
volumes:
  sonarqube_data:
  sonarqube_extensions:
  sonarqube_logs:
