server {
    listen 80;
    listen [::]:80;
    server_name lkequiz.pl;

    include       /etc/nginx/mime.types;
    root   /usr/share/nginx/html;
    index  index.html index.htm;

    error_page 404 =200 /index.html;

    access_log /usr/share/nginx/access.log;
    error_log /usr/share/nginx/error.log;

    location / {
        try_files $uri $uri/ /index.html =404;
        add_header Cache-Control "no-cache";
    }

    location /static {
        expires 1y;
        add_header Cache-Control "public";
    }

    location /api/ {
        proxy_pass http://api-gateway-svc:3000/;
    }
}