flyway.url=jdbc:postgresql://db.users.lkequiz.e-strix.pl:5432/users

flyway.driver=org.postgresql.Driver

flyway.user=user_db
flyway.password=postgres

flyway.locations=filesystem:/tmp/users/sql/

flyway.cleanDisabled=false